-- World VS — Seed Data: Countries (30)
INSERT INTO worldvs.countries (code, iso3, name_ko, name_en, name_ja, flag_emoji, capital_ko, capital_en, region, subregion) VALUES
('KR', 'KOR', '대한민국', 'South Korea', '大韓民国', '🇰🇷', '서울', 'Seoul', 'Asia', 'Eastern Asia'),
('JP', 'JPN', '일본', 'Japan', '日本', '🇯🇵', '도쿄', 'Tokyo', 'Asia', 'Eastern Asia'),
('CN', 'CHN', '중국', 'China', '中国', '🇨🇳', '베이징', 'Beijing', 'Asia', 'Eastern Asia'),
('TW', 'TWN', '대만', 'Taiwan', '台湾', '🇹🇼', '타이베이', 'Taipei', 'Asia', 'Eastern Asia'),
('US', 'USA', '미국', 'United States', 'アメリカ', '🇺🇸', '워싱턴 D.C.', 'Washington D.C.', 'Americas', 'Northern America'),
('CA', 'CAN', '캐나다', 'Canada', 'カナダ', '🇨🇦', '오타와', 'Ottawa', 'Americas', 'Northern America'),
('MX', 'MEX', '멕시코', 'Mexico', 'メキシコ', '🇲🇽', '멕시코시티', 'Mexico City', 'Americas', 'Central America'),
('BR', 'BRA', '브라질', 'Brazil', 'ブラジル', '🇧🇷', '브라질리아', 'Brasília', 'Americas', 'South America'),
('GB', 'GBR', '영국', 'United Kingdom', 'イギリス', '🇬🇧', '런던', 'London', 'Europe', 'Northern Europe'),
('FR', 'FRA', '프랑스', 'France', 'フランス', '🇫🇷', '파리', 'Paris', 'Europe', 'Western Europe'),
('DE', 'DEU', '독일', 'Germany', 'ドイツ', '🇩🇪', '베를린', 'Berlin', 'Europe', 'Western Europe'),
('IT', 'ITA', '이탈리아', 'Italy', 'イタリア', '🇮🇹', '로마', 'Rome', 'Europe', 'Southern Europe'),
('ES', 'ESP', '스페인', 'Spain', 'スペイン', '🇪🇸', '마드리드', 'Madrid', 'Europe', 'Southern Europe'),
('NL', 'NLD', '네덜란드', 'Netherlands', 'オランダ', '🇳🇱', '암스테르담', 'Amsterdam', 'Europe', 'Western Europe'),
('SE', 'SWE', '스웨덴', 'Sweden', 'スウェーデン', '🇸🇪', '스톡홀름', 'Stockholm', 'Europe', 'Northern Europe'),
('CH', 'CHE', '스위스', 'Switzerland', 'スイス', '🇨🇭', '베른', 'Bern', 'Europe', 'Western Europe'),
('RU', 'RUS', '러시아', 'Russia', 'ロシア', '🇷🇺', '모스크바', 'Moscow', 'Europe', 'Eastern Europe'),
('IN', 'IND', '인도', 'India', 'インド', '🇮🇳', '뉴델리', 'New Delhi', 'Asia', 'Southern Asia'),
('ID', 'IDN', '인도네시아', 'Indonesia', 'インドネシア', '🇮🇩', '자카르타', 'Jakarta', 'Asia', 'South-Eastern Asia'),
('VN', 'VNM', '베트남', 'Vietnam', 'ベトナム', '🇻🇳', '하노이', 'Hanoi', 'Asia', 'South-Eastern Asia'),
('TH', 'THA', '태국', 'Thailand', 'タイ', '🇹🇭', '방콕', 'Bangkok', 'Asia', 'South-Eastern Asia'),
('PH', 'PHL', '필리핀', 'Philippines', 'フィリピン', '🇵🇭', '마닐라', 'Manila', 'Asia', 'South-Eastern Asia'),
('SG', 'SGP', '싱가포르', 'Singapore', 'シンガポール', '🇸🇬', '싱가포르', 'Singapore', 'Asia', 'South-Eastern Asia'),
('MY', 'MYS', '말레이시아', 'Malaysia', 'マレーシア', '🇲🇾', '쿠알라룸푸르', 'Kuala Lumpur', 'Asia', 'South-Eastern Asia'),
('AU', 'AUS', '호주', 'Australia', 'オーストラリア', '🇦🇺', '캔버라', 'Canberra', 'Oceania', 'Australia and New Zealand'),
('NZ', 'NZL', '뉴질랜드', 'New Zealand', 'ニュージーランド', '🇳🇿', '웰링턴', 'Wellington', 'Oceania', 'Australia and New Zealand'),
('SA', 'SAU', '사우디아라비아', 'Saudi Arabia', 'サウジアラビア', '🇸🇦', '리야드', 'Riyadh', 'Asia', 'Western Asia'),
('TR', 'TUR', '튀르키예', 'Turkey', 'トルコ', '🇹🇷', '앙카라', 'Ankara', 'Asia', 'Western Asia'),
('EG', 'EGY', '이집트', 'Egypt', 'エジプト', '🇪🇬', '카이로', 'Cairo', 'Africa', 'Northern Africa'),
('ZA', 'ZAF', '남아프리카공화국', 'South Africa', '南アフリカ', '🇿🇦', '프리토리아', 'Pretoria', 'Africa', 'Southern Africa')
ON CONFLICT (code) DO NOTHING;
