-- World VS — Seed Data: Quiz Questions (Sample 20)
-- Full 1000 questions will be generated by quiz-generator.ts script
-- These are manually crafted questions

INSERT INTO worldvs.quiz_questions (id, type, difficulty, category, question_ko, correct_option_id, explanation_ko, related_indicator_id, is_active) VALUES
('Q000001', 'TRUE_FALSE', 'EASY', 'BASIC', '일본의 인구는 한국보다 2배 이상 많다.', 'YES', '일본의 인구는 약 1억 2천만 명, 한국은 약 5천만 명으로 일본이 2배 이상 많습니다.', 'population_total', true),
('Q000002', 'TRUE_FALSE', 'EASY', 'BASIC', '중국의 면적은 미국보다 넓다.', 'NO', '중국의 면적은 약 960만 km², 미국은 약 983만 km²로 미국이 더 넓습니다.', 'area_km2', true),
('Q000003', 'TRUE_FALSE', 'EASY', 'ECONOMY', '미국의 GDP는 중국보다 크다.', 'YES', '미국의 명목 GDP는 약 27조 달러, 중국은 약 18조 달러로 미국이 더 큽니다.', 'gdp_nominal', true),
('Q000004', 'TRUE_FALSE', 'EASY', 'SOCIETY', '한국의 기대수명은 80세 이상이다.', 'YES', '한국의 기대수명은 약 83.5세로 80세 이상입니다.', 'life_expectancy', true),
('Q000005', 'TRUE_FALSE', 'EASY', 'SOCIETY', '일본의 출산율은 한국보다 높다.', 'YES', '일본의 출산율은 약 1.20, 한국은 약 0.72로 일본이 더 높습니다.', 'fertility_rate', true),
('Q000006', 'TRUE_FALSE', 'EASY', 'MILITARY', '러시아의 전차 수는 미국보다 많다.', 'YES', '러시아는 약 12,500대, 미국은 약 4,640대로 러시아가 더 많습니다. (공개 자료 기반 추정치)', 'tanks', true),
('Q000007', 'TRUE_FALSE', 'EASY', 'CULTURE', '이탈리아의 유네스코 세계유산 수는 프랑스보다 많다.', 'YES', '이탈리아는 59곳, 프랑스는 49곳으로 이탈리아가 더 많습니다.', 'unesco_sites', true),
('Q000008', 'TRUE_FALSE', 'EASY', 'ENVIRONMENT', '중국은 세계에서 CO₂ 배출량이 가장 많은 국가 중 하나다.', 'YES', '중국의 연간 CO₂ 배출량은 약 114억 톤으로 세계 최대입니다.', 'co2_emissions', true),
('Q000009', 'TRUE_FALSE', 'EASY', 'BASIC', '싱가포르의 인구밀도는 한국보다 높다.', 'YES', '싱가포르는 약 8,100명/km², 한국은 약 516명/km²로 싱가포르가 훨씬 높습니다.', 'population_density', true),
('Q000010', 'TRUE_FALSE', 'EASY', 'ECONOMY', '스위스의 1인당 GDP는 미국보다 높다.', 'YES', '스위스는 약 10만 달러, 미국은 약 8.2만 달러로 스위스가 더 높습니다.', 'gdp_per_capita', true),
('Q000011', 'TRUE_FALSE', 'EASY', 'SOCIETY', '호주의 기대수명은 80세 이상이다.', 'YES', '호주의 기대수명은 약 83.3세로 80세 이상입니다.', 'life_expectancy', true),
('Q000012', 'TRUE_FALSE', 'EASY', 'MILITARY', '미국의 국방비는 세계 1위이다.', 'YES', '미국의 국방비는 약 8,160억 달러로 압도적인 세계 1위입니다.', 'defense_budget', true),
('Q000013', 'TRUE_FALSE', 'EASY', 'CULTURE', '스페인의 외국인 관광객 수는 프랑스보다 많다.', 'NO', '프랑스는 약 1억 명, 스페인은 약 8,500만 명으로 프랑스가 더 많습니다.', 'tourist_arrivals', true),
('Q000014', 'TRUE_FALSE', 'EASY', 'BASIC', '캐나다의 면적은 중국보다 넓다.', 'YES', '캐나다는 약 998만 km², 중국은 약 960만 km²로 캐나다가 더 넓습니다.', 'area_km2', true),
('Q000015', 'TRUE_FALSE', 'EASY', 'ECONOMY', '한국의 인터넷 사용률은 90% 이상이다.', 'YES', '한국의 인터넷 사용률은 약 97%로 90% 이상입니다.', 'internet_penetration', true),
('Q000016', 'TRUE_FALSE', 'EASY', 'SOCIETY', '인도의 중위연령은 30세 미만이다.', 'NO', '인도의 중위연령은 약 28.4세로 30세 미만입니다. 정답은 "예"입니다.', 'median_age', true),
('Q000017', 'TRUE_FALSE', 'EASY', 'ENVIRONMENT', '에베레스트산은 중국과 네팔 국경에 있다.', 'YES', '에베레스트산(8,849m)은 중국과 네팔 국경에 위치하며 중국 최고봉입니다.', 'highest_peak', true),
('Q000018', 'TRUE_FALSE', 'EASY', 'MILITARY', '한국의 전투기 수는 일본보다 많다.', 'YES', '한국은 약 402대, 일본은 약 217대로 한국이 더 많습니다. (공개 자료 기반 추정치)', 'fighter_aircraft', true),
('Q000019', 'TRUE_FALSE', 'EASY', 'CULTURE', '독일의 유네스코 세계유산 수는 50곳 이상이다.', 'YES', '독일은 52곳의 유네스코 세계유산을 보유하고 있습니다.', 'unesco_sites', true),
('Q000020', 'TRUE_FALSE', 'EASY', 'BASIC', '일본의 인구밀도는 한국보다 낮다.', 'YES', '일본은 약 325명/km², 한국은 약 516명/km²로 일본이 더 낮습니다.', 'population_density', true)
ON CONFLICT (id) DO NOTHING;

-- Options for TRUE_FALSE questions
INSERT INTO worldvs.quiz_options (question_id, option_id, text_ko, sort_order) VALUES
('Q000001', 'YES', '예', 0),
('Q000001', 'NO', '아니오', 1),
('Q000002', 'YES', '예', 0),
('Q000002', 'NO', '아니오', 1),
('Q000003', 'YES', '예', 0),
('Q000003', 'NO', '아니오', 1),
('Q000004', 'YES', '예', 0),
('Q000004', 'NO', '아니오', 1),
('Q000005', 'YES', '예', 0),
('Q000005', 'NO', '아니오', 1),
('Q000006', 'YES', '예', 0),
('Q000006', 'NO', '아니오', 1),
('Q000007', 'YES', '예', 0),
('Q000007', 'NO', '아니오', 1),
('Q000008', 'YES', '예', 0),
('Q000008', 'NO', '아니오', 1),
('Q000009', 'YES', '예', 0),
('Q000009', 'NO', '아니오', 1),
('Q000010', 'YES', '예', 0),
('Q000010', 'NO', '아니오', 1),
('Q000011', 'YES', '예', 0),
('Q000011', 'NO', '아니오', 1),
('Q000012', 'YES', '예', 0),
('Q000012', 'NO', '아니오', 1),
('Q000013', 'YES', '예', 0),
('Q000013', 'NO', '아니오', 1),
('Q000014', 'YES', '예', 0),
('Q000014', 'NO', '아니오', 1),
('Q000015', 'YES', '예', 0),
('Q000015', 'NO', '아니오', 1),
('Q000016', 'YES', '예', 0),
('Q000016', 'NO', '아니오', 1),
('Q000017', 'YES', '예', 0),
('Q000017', 'NO', '아니오', 1),
('Q000018', 'YES', '예', 0),
('Q000018', 'NO', '아니오', 1),
('Q000019', 'YES', '예', 0),
('Q000019', 'NO', '아니오', 1),
('Q000020', 'YES', '예', 0),
('Q000020', 'NO', '아니오', 1)
ON CONFLICT (question_id, option_id) DO NOTHING;

-- Fix Q000016: India median age is 28.4 which IS under 30, so answer should be YES
UPDATE worldvs.quiz_questions SET correct_option_id = 'YES', explanation_ko = '인도의 중위연령은 약 28.4세로 30세 미만입니다.' WHERE id = 'Q000016';
